language: java
install: true
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
  - stage: test
    name: "Unit tests - OracleJDK 8"
    script: mvn -B -DtestLogLevel=OFF test
    jdk: oraclejdk8
  - stage: deploy
    name: "Deploy to Sonatype's snapshots repository"
    if: type != pull_request
    script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
    - secure: "u6+7M1q/NDvw4WF287KtaK+F9tiVkI5WDXMdM6ttGz9kfKB50gwQRtWz4XwUxolFzc6Gs/tB6XV6K5De0LskIGPNxDt59ucIWpIjCCA9Qdpqdx6bqQ8VqbCOfq+r0vi+zhp6LkUi+o9s0Ni9HDmEUCEHDWF4NSQlvanKwQRzcCpfi4NuNKGoKtvlarOx5omj6S90hRZZdefvbkxCGVe4Y6Ahubv7FiQ/Ji81DkP1cBl45LMYTcPnMu/UtxntKNDmJM0h3hh+uHY6W6Z4sAKdkm1PcVou79smTBBMtamojLWGDzT3rCmyS8Aoy4UxVunQqkVkCGTYALtZI4LWD8A5514iadTC2ULI5TsYuD0N9fIwHvGqa70+QtnDKNWFCZFkxPO8oVtlWsJJDIHJkj876+ULhKDGPSD+fOsV0aHdzxtZ2uK4qtMQmjhQRYdRqxuAZDSYJ46g4olcNn9WPN3loLNVuPVumEihpjxaP9VBKNhjR773d65IwMjm2jCWXCmIXoymxSK2T7GS6VofyeBaz8YR6DGkQA/MQe52BCabyve7eioTkJl4n+qb/yUsVY2q9dl5DsAYsC4l/WJ8SzmnffLqj93gRwpzIyuJtiKUef9HHzUASh+MZYHRHlIV0LzLpLSErMLwehxsYpuKzjdvb7qqjLoIgIc3bGBXTsZEYz4="
    on_success: always
    on_failure: always
